# Generated by Django 5.1.2 on 2025-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Debito'), ('credito', 'Credito'), ('cheque', 'Cheque')], max_length=100, null=True),
        ),
    ]
