# Generated by Django 5.1.2 on 2025-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_boleta_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='numero_cheque',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
