# Generated by Django 5.1.2 on 2025-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_boleta_año_boleta_numero_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='numero_talonario',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
