# Generated by Django 5.1.2 on 2025-01-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_boleta_numero_talonario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='recibido',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='rut',
        ),
    ]
