# Generated by Django 5.1.2 on 2025-01-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_boleta_firma_remove_boleta_recibido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='link_4',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='link_5',
        ),
    ]
