# Generated by Django 5.1.2 on 2025-02-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_proyecto_enlace_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='correo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='telefono',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_documento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
