# Generated by Django 5.1.2 on 2025-06-17 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_contactos_correo_alter_contactos_telefono_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='proceso',
            field=models.CharField(blank=True, choices=[('terminado', 'Terminado'), ('no aplica', 'No Aplica'), ('pendiente', 'Pendiente')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_correo', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_total', models.PositiveIntegerField(help_text='Monto total a pagar en pesos chilenos')),
                ('monto_pagado', models.PositiveIntegerField(default=0, help_text='Monto ya pagado en pesos chilenos')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('completo', 'Pagado Completo'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del servicio o producto', max_length=1000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='myapp.proyecto')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.PositiveIntegerField(help_text='Monto del pago en pesos chilenos')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('cheque', 'Cheque')], max_length=20)),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de transferencia, cheque, etc.', max_length=100, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('notas', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pago_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='myapp.pagocliente')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
