# Generated by Django 5.1.2 on 2025-07-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_proyecto_proceso_pagocliente_detallepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas internas del proyecto', max_length=1000, null=True),
        ),
    ]
